site_name: PAS model
site_description: 'PIXEL PAS model description and user guide'
site_author: 'CATIE'

# this allows visualizing content in github as anonympus user without having to log in
edit_uri: blob/master/docs/

theme: readthedocs

# we will use the same style as for the general PIXEL documentation hub (based on FIWARE and a readthedocs theme)
extra_css:
    - css/pixel_a.css
    - css/pixel_b.css
    - css/monokai_sublime_.css
    - css/pigments-monokai.css

repo_url: https://github.com/ES-catie/docs-PAS-model

nav:
    - Home: index.md
    - OT Framework: 'ot_framework.md'
    - User's Guide: 'user_guide.md'
    - Developer's Guide: 'devel_guide.md'


copyright: Apache License 2.0

extra:
  version: 1.0.0
  color: 26b3c3
